### ISSUE TITLE
Ram Crashes when trying to run the model.

### ISSUE THREAD

**Issue by nikhilbyte** [GarfieldLyu/OCR_POST_DE#1]
I've tried decreasing the batch size as well.
System Config: Ram 25GB
GPU: 15GB(P100)

**Comment by GarfieldLyu** [comment]
Hey,
can you be more specific, which implementation or script are you running?

**Comment by nikhilbyte** [comment]
I'm running the ocr_corrector.py file from keras_implement folder. 
Here are the experiment settings:
Tokenizer: Char

Arguments:

glu =0
return_blocks=0
kernels = [3]
layer_num=3
units=256
embedding_dim=128
epochs=10
batch=8
n_features=400
custom=0
alpha=0.1
use_cnn=1
model_dir = "model_output"
name = "sanskrit_ocr_corrector"

**Comment by GarfieldLyu** [comment]
How about your input sentence length and vocabulary size? With Keras
implementation, the target tensor has to be converted to one-hot
representation for the training, this might be the problem. My input
sentences tokenized to characters are usually no more than 100.

**Comment by nikhilbyte** [comment]
These are my input and output dimension.
Any work around for this ? 
<img width="647" alt="Screenshot 2022-03-29 at 2 27 06 PM" src="https://user-images.githubusercontent.com/62005061/160574626-7e0f9d8e-05db-4d8c-ad97-151fcd942986.png">

**Comment by GarfieldLyu** [comment]
This seems quite big to handle at once for the Keras implementation if your
vocab is 400. You can try to reduce the data size and check if it works.
Unfortunately for Keras implementation, there is no data iteration function
like the torch version. If you just want some quick correction results, I
suggest you try the torch version first, since it will take some time for
me to add the data loading process for Keras at the moment.
